Repository MojoOno/TheMovieDatabase, pull requests merged in 2025-02, with the labels that each got.

#10 feat-movielist-in-grenre
  src/main/java/dat/entities/Genre.java
Labels: question

#15 MoveInfo-branch
  src/main/java/dat/Main.java
  src/main/java/dat/dtos/MovieDTO.java
  src/main/java/dat/services/MovieService.java
Labels: enhancement

#17 EntityRefactoring-branch
  src/main/java/dat/daos/ActorDAO.java
  src/main/java/dat/daos/DirectorDAO.java
  src/main/java/dat/dtos/ActorDTO.java
  src/main/java/dat/dtos/CreditDTO.java
  src/main/java/dat/dtos/CreditResponseDTO.java
  src/main/java/dat/dtos/MovieDTO.java
  src/main/java/dat/entities/Actor.java
  src/main/java/dat/entities/Credit.java
  src/main/java/dat/entities/Director.java
  src/main/java/dat/entities/Genre.java
  src/main/java/dat/entities/Movie.java
  src/main/java/dat/services/MovieService.java
Labels: enhancement

#19 PersistMovieToDB-Branch
  src/main/java/dat/Main.java
  src/main/java/dat/dtos/MovieDTO.java
  src/main/java/dat/entities/Movie.java
Labels: enhancement

#23 CreditToDB-Branch
  src/main/java/dat/Main.java
  src/main/java/dat/config/HibernateConfig.java
  src/main/java/dat/daos/CreditDAO.java
  src/main/java/dat/daos/GenreDAO.java
  src/main/java/dat/daos/MovieDAO.java
  src/main/java/dat/dtos/CreditDTO.java
  src/main/java/dat/dtos/MovieDTO.java
  src/main/java/dat/entities/Credit.java
  src/main/java/dat/entities/Movie.java
  src/main/java/dat/services/MovieService.java
Labels: help wanted

#25 refactor-dao-apiexceptions-streamline
  src/main/java/dat/Main.java
  src/main/java/dat/daos/CreditDAO.java
  src/main/java/dat/daos/GenreDAO.java
  src/main/java/dat/daos/IDAO.java
  src/main/java/dat/daos/MovieDAO.java
  src/main/java/dat/daos/SauronDAO.java
Labels: enhancement

#28 newServiceClasses
  src/main/java/dat/Main.java
  src/main/java/dat/daos/SauronDAO.java
  src/main/java/dat/services/APIReaderService.java
  src/main/java/dat/services/DBReaderService.java
  src/main/java/dat/services/MovieService.java
Labels: enhancement
